<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "slavlee_charcount"
 *
 * Auto generated by Extension Builder 2021-07-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'CharacterCount',
    'description' => 'This plugin display the amount of characters that you put inside a textarea.',
    'category' => 'plugin',
    'author' => 'Kevin Chileong Lee',
    'author_email' => 'support@slavlee.de',
    'state' => 'stable',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
